BoxLayout:
    orientation: 'vertical'

    MDToolbar:
        title: "Bottom Navbar"
        md_bg_color: .2,.2,.2,1


    MDBottomNavigation:

        MDBottomNavigationItem:
            name: 'screen 1'
            text: "Full Tank List"
            icon: 'format-list-bulleted'

            MDLabel:
                text: "alle Fahrzeuge"
                halign: 'center'

        MDBottomNavigationItem:
            name: 'screen 2'
            text: "Youtube"
            icon: 'youtube'

            MDLabel:
                text: "official youtube"
                halign: 'center'

        MDBottomNavigationItem:
            name: 'screen 3'
            text: "Instagram"
            icon: 'instagram'

            MDLabel:
                text: "official instagram"
                halign: 'center'